### ISSUE TITLE
Add php close tag for comment

### ISSUE THREAD

**Issue by arunwac** [caizhengxin/vscodefileheader#1]
Hi, this is a request, but can you add a close tag for php files? Or create a setting where we can chose whether to add the close tag or not? This is because the comment header without close tags messes up files in laravel because many of these files are autogenerated with `<?php` tags, so the extension creating another `<?` tag at header really messes things up, forcing me to manually close them. This would be fixed if the header has a close tag `?>`

**Comment by caizhengxin** [comment]
Sorry, I did n’t see it in time. What do you mean by removing `<??>`?

**Comment by caizhengxin** [comment]
Sorry, I did n’t see it in time. What do you mean by removing `<??>`?

**Comment by caizhengxin** [comment]
> Hi, this is a request, but can you add a close tag for php files? Or create a setting where we can chose whether to add the close tag or not? This is because the comment header without close tags messes up files in laravel because many of these files are autogenerated with

Sorry, I did n’t see it in time. What do you mean by removing `<??>`?

**Comment by arunwac** [comment]
Sorry about that, looks like the rich text editor on github parsed the `<?php`  tags. Updated the issue. Please read again

**Comment by caizhengxin** [comment]
> Sorry about that, looks like the rich text editor on github parsed the `<?php` tags. Updated the issue. Please read again

Your problem is known and will be fixed as soon as possible, thank you

**Comment by caizhengxin** [comment]
See v0.3.2
