### ISSUE TITLE
Issues with 0.9.0

### ISSUE THREAD

**Issue by maurotoro** [caizhengxin/vscodefileheader#13]
Somehow after this update, the extension stopped working in all my installations, I use it under GNU/Linux, OSX and Window. Downgrading to 0.8.0 did solve the issue, but it feels strange.

I don't know why this happened, nor know enough about VSCode to give more meaningful details. If you could tell me how to do it, I can give debug info.

Many thanks for a nice extension! 

Suerte!

**Comment by caizhengxin** [comment]
> Somehow after this update, the extension stopped working in all my installations, I use it under GNU/Linux, OSX and Window. Downgrading to 0.8.0 did solve the issue, but it feels strange.
> 
> I don't know why this happened, nor know enough about VSCode to give more meaningful details. If you could tell me how to do it, I can give debug info.
> 
> Many thanks for a nice extension!
> 
> Suerte!

Hi, Temporary solution

![image](https://user-images.githubusercontent.com/21964908/124615207-9ecbe780-dea7-11eb-97b4-6c9a4d4326a3.png)
