### ISSUE TITLE
hope insert comment to already existing tag (希望能把注释插入到已经存在的标签)

### ISSUE THREAD

**Issue by Delevin888** [caizhengxin/vscodefileheader#15]
in my vue3 + ts + vite project
 (在我vue3+ts+vite的项目里)
i create vue file ues snippet `vbase-3-ts-setup` with `sdras.vue-vscode-snippets` extension.
(我用 `sdras.vue-vscode-snippets` 扩展的  `vbase-3-ts-setup`  片段创建了一个vue文件)

and then insert comment to file will get result 
(然后插入注释到文件会得到结果)

```vue
<script>
/**
 * @Author: HuChaoyang
 * @Date:   2022-03-01 11:02:27
 * @Last Modified by:   HuChaoyang
 * @Last Modified time: 2022-03-01 11:24:30
 */
</script>
<template>
  <div></div>
</template>

<script setup lang="ts"></script>

<style scoped></style>
```

vite console will print error
(vite 的控制台会打印错误日志)
```
Internal server error: [@vue/compiler-sfc] <script> and <script setup> must have the same language type.
```

perfect if it can be inserted into an existing script tag.
(如果它可以插入现有的脚本标签，那就完美了。)

**Comment by caizhengxin** [comment]
嗨，你可以采用自定义模板实现，可以参考使用手册README.md

**Comment by caizhengxin** [comment]
> in my vue3 + ts + vite project (在我vue3+ts+vite的项目里) i create vue file ues snippet `vbase-3-ts-setup` with `sdras.vue-vscode-snippets` extension. (我用 `sdras.vue-vscode-snippets` 扩展的 `vbase-3-ts-setup` 片段创建了一个vue文件)
> 
> and then insert comment to file will get result (然后插入注释到文件会得到结果)
> 
> ```
> <script>
> /**
>  * @Author: HuChaoyang
>  * @Date:   2022-03-01 11:02:27
>  * @Last Modified by:   HuChaoyang
>  * @Last Modified time: 2022-03-01 11:24:30
>  */
> </script>
> <template>
>   <div></div>
> </template>
> 
> <script setup lang="ts"></script>
> 
> <style scoped></style>
> ```
> 
> vite console will print error (vite 的控制台会打印错误日志)
> 
> ```
> Internal server error: [@vue/compiler-sfc] <script> and <script setup> must have the same language type.
> ```
> 
> perfect if it can be inserted into an existing script tag. (如果它可以插入现有的脚本标签，那就完美了。)

嗨，你可以采用自定义模板实现，可以参考使用手册README.md

**Comment by Delevin888** [comment]
亲，没有看到可配置的注释占位符呢？

> > in my vue3 + ts + vite project (在我vue3+ts+vite的项目里) i create vue file ues snippet `vbase-3-ts-setup` with `sdras.vue-vscode-snippets` extension. (我用 `sdras.vue-vscode-snippets` 扩展的 `vbase-3-ts-setup` 片段创建了一个vue文件)
> > and then insert comment to file will get result (然后插入注释到文件会得到结果)
> > ```
> > <script>
> > /**
> >  * @Author: HuChaoyang
> >  * @Date:   2022-03-01 11:02:27
> >  * @Last Modified by:   HuChaoyang
> >  * @Last Modified time: 2022-03-01 11:24:30
> >  */
> > </script>
> > <template>
> >   <div></div>
> > </template>
> > 
> > <script setup lang="ts"></script>
> > 
> > <style scoped></style>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > vite console will print error (vite 的控制台会打印错误日志)
> > ```
> > Internal server error: [@vue/compiler-sfc] <script> and <script setup> must have the same language type.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > perfect if it can be inserted into an existing script tag. (如果它可以插入现有的脚本标签，那就完美了。)
> 
> 嗨，你可以采用自定义模板实现，可以参考使用手册README.md

**Comment by caizhengxin** [comment]
> <script setup lang="ts">

嗨，不太明白什么意思，你可以给出之前的内容，以及插入头文件之后的内容样式。
