### ISSUE TITLE
 Does the template file support jinja2 syntax？

### ISSUE THREAD

**Issue by shenchucheng** [caizhengxin/vscodefileheader#16]
I changed the template file `vscodefileheader/template/body/Python.tmpl` using jinja2 syntax to suported if/else condition, but it not worked. 
```tml

{%- if fileBasename.startswith('test_') -%}

import unittest


if __name__ == "__main__":
    unittest.main()

{% else %}
def main():
    pass


if __name__ == "__main__":
    main()
{% endif %}

```

**Comment by caizhengxin** [comment]
> I changed the template file `vscodefileheader/template/body/Python.tmpl` using jinja2 syntax to suported if/else condition, but it not worked.
> 
> ```
> {%- if fileBasename.startswith('test_') -%}
> 
> import unittest
> 
> 
> if __name__ == "__main__":
>     unittest.main()
> 
> {% else %}
> def main():
>     pass
> 
> 
> if __name__ == "__main__":
>     main()
> {% endif %}
> ```

http://aui.github.io/art-template/docs/
