### ISSUE TITLE
您好，我想请问一下插件的快捷键是什么，我试了ctrl+alt+i是不正确的，您的文档中好像也没有体现！谢谢！

### ISSUE THREAD

**Issue by adjgh** [caizhengxin/vscodefileheader#17]

**Comment by caizhengxin** [comment]
> 嗨，这个是Windows操作命令，其实不用特意按快捷键，你只需要保存文件就会自动插入头部注释

嗨，这个是Windows操作命令，其实不用特意按快捷键，你只需要保存文件就会自动插入头部注释

**Comment by caizhengxin** [comment]
> _No description provided._

嗨，这个是Windows操作命令，其实不用特意按快捷键，你只需要保存文件就会自动插入头部注释
