### ISSUE TITLE
infinite loop insertion

### ISSUE THREAD

**Issue by lsalomon** [caizhengxin/vscodefileheader#19]
hello !

I tried to use the extension but when creating my file with a custom template, I have an infinite loop insertion of the template...

I saw there is a `is_header_exists` property to set, but as it is a per template different value, I don't know how to solve / use it :(

here is my current config :
```
  "fileheader.custom_template_path": "[My home path]/.vscode/template/",
  "fileheader.author": "lsalomon",
  "fileheader.header_max_line": 20,
  "fileheader.save": true,
  "fileheader.open": true,
  "fileheader.dateformat": "YYYY-MM-DD HH:mm:ss",
  "fileheader.body": true,
  "fileheader.file_suffix_mapping": {
      ".po": "po",
      ...
  },
  "fileheader.ignore": [
    ".tmpl"
  ]
```

here is the tmpl content :
```
msgid ""
msgstr ""
"Project-Id-Version: \n"
"POT-Creation-Date: {{create_time}}\n"
"PO-Revision-Date: {{last_modified_time}}\n"
"Last-Translator: {{last_modified_by}}\n"
"Language-Team: \n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Generator: Poedit 3.2\n"
```

I'm on Mac OSX :
```
Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

Thanks

**Comment by caizhengxin** [comment]
> 

Hi, currently `is_header_exists` is effective for the global template, generally judge the first line.

**Comment by joshhubert-dsp** [comment]
Adding `is_header_exists` fixed the infinite insertion loop for me, but now the modified time doesn't update after the first time it's saved, when I use my custom template. 

Here's my `Python.tmpl`:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
FILE NAME

DESCRIPTION

@Author  :   {{author}}
@Created :   {{create_time}}
@Modified:   {{last_modified_time}}
@Company :   {{company}}
@File    :   {{relativeFile}}
@Dir     :   {{fileDirname}}
@Version :   1.0
"""
```

**Comment by caizhengxin** [comment]
![image](https://user-images.githubusercontent.com/21964908/219372037-9737a767-32ca-471e-a5c6-ed50f0cde5a6.png)

Sorry, I just saw that the current time before ":" cannot be modified.

**Comment by caizhengxin** [comment]
> Adding `is_header_exists` fixed the infinite insertion loop for me, but now the modified time doesn't update after the first time it's saved, when I use my custom template.
> 
> Here's my `Python.tmpl`:
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> """
> FILE NAME
> 
> DESCRIPTION
> 
> @Author  :   {{author}}
> @Created :   {{create_time}}
> @Modified:   {{last_modified_time}}
> @Company :   {{company}}
> @File    :   {{relativeFile}}
> @Dir     :   {{fileDirname}}
> @Version :   1.0
> """
> ```

![image](https://user-images.githubusercontent.com/21964908/219372373-b70a6d49-e8bc-4d4f-8436-3827f08c74f0.png)

Sorry, I just saw that the current time before ":" cannot be modified.

**Comment by caizhengxin** [comment]
> Adding `is_header_exists` fixed the infinite insertion loop for me, but now the modified time doesn't update after the first time it's saved, when I use my custom template.
> 
> Here's my `Python.tmpl`:
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> """
> FILE NAME
> 
> DESCRIPTION
> 
> @Author  :   {{author}}
> @Created :   {{create_time}}
> @Modified:   {{last_modified_time}}
> @Company :   {{company}}
> @File    :   {{relativeFile}}
> @Dir     :   {{fileDirname}}
> @Version :   1.0
> """
> ```

Hi, I'm sorry, can update v0.10.1 version.

**Comment by caizhengxin** [comment]
> Adding `is_header_exists` fixed the infinite insertion loop for me, but now the modified time doesn't update after the first time it's saved, when I use my custom template.
> 
> Here's my `Python.tmpl`:
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> 
> """
> FILE NAME
> 
> DESCRIPTION
> 
> @Author  :   {{author}}
> @Created :   {{create_time}}
> @Modified:   {{last_modified_time}}
> @Company :   {{company}}
> @File    :   {{relativeFile}}
> @Dir     :   {{fileDirname}}
> @Version :   1.0
> """
> ```

Hi, can update to v0.10.4
