### ISSUE TITLE
when I inserted a file header, I can't save the file. 

### ISSUE THREAD

**Issue by XuhaoShao** [caizhengxin/vscodefileheader#2]
when I inserted a file header, I can't save the file, either pressing ctrl+s or clicking the save menu.  But after I delete the line '# @Last Modified time: 2020-03-13 21:02:25', it works. So I guess, this updating seconds in this line cause the problem. Are there any solutions?

**Comment by XuhaoShao** [comment]
OK, after installing TSLint plugins in vs code, everything works well.

**Comment by caizhengxin** [comment]
Hi, This is a bug, it may be a problem with vscode version, it was not
needed before

Xuhao Shao <notifications@github.com> 于2020年3月14日周六 上午10:43写道：

**Comment by XuhaoShao** [comment]
Amazing! It failed again after I reload the VScode, although I've installed the TSLint. 
And Maybe, as you said, It's the version of VScode caused it, because I update the VScode to the latest and the bug appears.  So what I can do is waiting for the next version of VSCode or go back for the old version?

**Comment by caizhengxin** [comment]
> Amazing! It failed again after I reload the VScode, although I've installed the TSLint.
> And Maybe, as you said, It's the version of VScode caused it, because I update the VScode to the latest and the bug appears. So what I can do is waiting for the next version of VSCode or go back for the old version?

Bugs that can be fixed。

**Comment by caizhengxin** [comment]
> Amazing! It failed again after I reload the VScode, although I've installed the TSLint.
> And Maybe, as you said, It's the version of VScode caused it, because I update the VScode to the latest and the bug appears. So what I can do is waiting for the next version of VSCode or go back for the old version?

Update v0.4.1

**Comment by XuhaoShao** [comment]
> > Amazing! It failed again after I reload the VScode, although I've installed the TSLint.
> > And Maybe, as you said, It's the version of VScode caused it, because I update the VScode to the latest and the bug appears. So what I can do is waiting for the next version of VSCode or go back for the old version?
> 
> Update v0.4.1

YES! 
It works like before. Thank you!
