### ISSUE TITLE
How to set settings.json so that the output is & instead of &# 38; ?

### ISSUE THREAD

**Issue by gzhang** [caizhengxin/vscodefileheader#23]
I have defined the copyright in the settings.json
"fileheader.other_config": {
        "Copyright": "Sch Geophys & Informat Technol"
    },

however, it output in Julia code fileheader as follows:
# @Copyright: Sch Geophys "&#38"; Informat Technol

How to fix it?
thanks.

**Comment by gzhang** [comment]
I have tried some suggestions on the internet, but they do not work. such as: 
(1) adding the comment "Escape": false,
(2) replace the & by \\&, or \ampt
and so on.

**Comment by caizhengxin** [comment]
> I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by \&, or \ampt and so on.

Hi, I'm sorry. I just saw it. have time I see how to fix.

**Comment by caizhengxin** [comment]
> I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by \&, or \ampt and so on.

Hi, I'm sorry, can update v0.10.1 version.

**Comment by gzhang** [comment]
![image](https://github.com/caizhengxin/vscodefileheader/assets/35960491/5d185e2e-1a23-4d02-9483-490b47b32ff3)

Thank you, but with the current version update, the header file cannot be inserted anymore.

**Comment by gzhang** [comment]
> > I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by &, or \ampt and so on.
> 
> Hi, I'm sorry, can update v0.10.1 version.

![image](https://github.com/caizhengxin/vscodefileheader/assets/35960491/29836097-53be-47eb-8c49-cf7a5009cfe4)

Thank you, but with the current version update, the header file cannot be inserted anymore.

**Comment by caizhengxin** [comment]
> > > I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by &, or \ampt and so on.
> > 
> > 
> > Hi, I'm sorry, can update v0.10.1 version.
> 
> ![image](https://private-user-images.githubusercontent.com/35960491/311476513-29836097-53be-47eb-8c49-cf7a5009cfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwMzU5ODYsIm5iZiI6MTcxMDAzNTY4NiwicGF0aCI6Ii8zNTk2MDQ5MS8zMTE0NzY1MTMtMjk4MzYwOTctNTNiZS00N2ViLThjNDktY2Y3YTUwMDljZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAxNTQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MDQ3NWEzMTU3NGVkMDgxZDFkMWE4OWNhZDZiMGRlYTUxNzY5MzRkYzhiMzNlMDg2YTQ3NmQ5YWE5OTlmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YdwxsLBHGPQUkpCuqOXIwC40QnJ0J74XBr6OWJV-3E)
> 
> Thank you, but with the current version update, the header file cannot be inserted anymore.

Ah, my local debugging test yesterday was OK. and it was Ok to install v0.10.1 on another computer, Let me see again.

**Comment by caizhengxin** [comment]
> > > I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by &, or \ampt and so on.
> > 
> > 
> > Hi, I'm sorry, can update v0.10.1 version.
> 
> ![image](https://private-user-images.githubusercontent.com/35960491/311476513-29836097-53be-47eb-8c49-cf7a5009cfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDAyNjIsIm5iZiI6MTcxMDAzOTk2MiwicGF0aCI6Ii8zNTk2MDQ5MS8zMTE0NzY1MTMtMjk4MzYwOTctNTNiZS00N2ViLThjNDktY2Y3YTUwMDljZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAzMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OGUyZDM1NmRmYmVhNGU4MGIxNjlhMWMwMzExMjEwODRlOGExMzVkMGEwNThmNDMzYWYxOGUzZmUzNzAyNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZMkSFOP3Zyhc5Sb8YVFqpGtq6C4r-TddUC0XKo9ZNs)
> 
> Thank you, but with the current version update, the header file cannot be inserted anymore.

Thanks, can update to v0.10.4 version.  because there are too many files when packaging, I filtered the `node_modules` directory leading to problems, and then I can test it through the vsix local package first, and then publish it to avoid this problem.

**Comment by gzhang** [comment]
> > > > I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by &, or \ampt and so on.
> > > 
> > > 
> > > Hi, I'm sorry, can update v0.10.1 version.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/35960491/311476513-29836097-53be-47eb-8c49-cf7a5009cfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDAyNjIsIm5iZiI6MTcxMDAzOTk2MiwicGF0aCI6Ii8zNTk2MDQ5MS8zMTE0NzY1MTMtMjk4MzYwOTctNTNiZS00N2ViLThjNDktY2Y3YTUwMDljZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAzMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OGUyZDM1NmRmYmVhNGU4MGIxNjlhMWMwMzExMjEwODRlOGExMzVkMGEwNThmNDMzYWYxOGUzZmUzNzAyNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZMkSFOP3Zyhc5Sb8YVFqpGtq6C4r-TddUC0XKo9ZNs)
> > Thank you, but with the current version update, the header file cannot be inserted anymore.
> 
> Thanks, can update to v0.10.4 version. because there are too many files when packaging, I filtered the `node_modules` directory leading to problems, and then I can test it through the vsix local package first, and then publish it to avoid this problem.

Thank you; the new version is already working.

But there is also an issue: after the update, the user defined Julia. tmpl has been cleaned up and needs to be redefined.

Thank you.

Perfectly solved the problem of escaping characters.

**Comment by caizhengxin** [comment]
> > > > > I have tried some suggestions on the internet, but they do not work. such as: (1) adding the comment "Escape": false, (2) replace the & by &, or \ampt and so on.
> > > > 
> > > > 
> > > > Hi, I'm sorry, can update v0.10.1 version.
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/35960491/311476513-29836097-53be-47eb-8c49-cf7a5009cfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNDAyNjIsIm5iZiI6MTcxMDAzOTk2MiwicGF0aCI6Ii8zNTk2MDQ5MS8zMTE0NzY1MTMtMjk4MzYwOTctNTNiZS00N2ViLThjNDktY2Y3YTUwMDljZmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDAzMDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3OGUyZDM1NmRmYmVhNGU4MGIxNjlhMWMwMzExMjEwODRlOGExMzVkMGEwNThmNDMzYWYxOGUzZmUzNzAyNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uZMkSFOP3Zyhc5Sb8YVFqpGtq6C4r-TddUC0XKo9ZNs)
> > > Thank you, but with the current version update, the header file cannot be inserted anymore.
> > 
> > 
> > Thanks, can update to v0.10.4 version. because there are too many files when packaging, I filtered the `node_modules` directory leading to problems, and then I can test it through the vsix local package first, and then publish it to avoid this problem.
> 
> Thank you; the new version is already working.
> 
> But there is also an issue: after the update, the user defined Julia. tmpl has been cleaned up and needs to be redefined.
> 
> Thank you.
> 
> Perfectly solved the problem of escaping characters.

1. You can set a custom template path, this will not be emptied. 
2. You can also set a git address that will automatically clone templates.
