### ISSUE TITLE
Support Variables

### ISSUE THREAD

**Issue by rollecode** [caizhengxin/vscodefileheader#3]
Hi! Great plugin. Works best of the all fileheader plugins out there in my opinion. However, I'd like to assign [Visual Studio Code Variables](https://code.visualstudio.com/docs/editor/variables-reference) to a template. Currently cannot do that. For example, template like this would be nice to have:

```
// @author:       {{author}}, {{company}}
// @date:         {{create_time}}
// @last Modified by:   {{last_modified_by}}
// @last Modified time: {{last_modified_time}}
//
// @package ${workspaceFolder}
 ```

**Comment by caizhengxin** [comment]
> Hi! Great plugin. Works best of the all fileheader plugins out there in my opinion. However, I'd like to assign [Visual Studio Code Variables](https://code.visualstudio.com/docs/editor/variables-reference) to a template. Currently cannot do that. For example, template like this would be nice to have:
> 
> ```
> // @author:       {{author}}, {{company}}
> // @date:         {{create_time}}
> // @last Modified by:   {{last_modified_by}}
> // @last Modified time: {{last_modified_time}}
> //
> // @package ${workspaceFolder}
> ```

Thank you for your suggestion, consider joining.
