### ISSUE TITLE
File Template issue

### ISSUE THREAD

**Issue by Preetam2114** [caizhengxin/vscodefileheader#4]
The header keeps on adding to the file like a for loop when a custom template is added.

**Comment by caizhengxin** [comment]
> The header keeps on adding to the file like a for loop when a custom template is added.

vscode version and vscodefileheader version ?

**Comment by caizhengxin** [comment]
> The header keeps on adding to the file like a for loop when a custom template is added.

see custom template comment?

**Comment by dbellavista** [comment]
@caizhengxin I also have this problem

* code version 1.49.2
* VsCodeFileHeader version 0.5.0

Out of the box it works fine, but when I setup a custom template the problem occurs.

```
    "fileheader.body": true,
    "fileheader.author": "Daniele Bellavista",
    "fileheader.custom_template_path": "C:\\Users\\danie\\source\\VsCode\\templates",
    "fileheader.ignore": ["*.tmpl"]
```

```
PS C:\Users\danie\source\VsCode\templates> cat .\header\JavaScript.tmpl

/*
 * @Author: {{author}}
 * @Date:   {{create_time}}
 * @Last Modified by:   {{last_modified_by}}
 * @Last Modified time: {{last_modified_time}}
 */
```

When creating a Javascript file, the header is inserted continuously until the file is closed.

**Comment by caizhengxin** [comment]
> @caizhengxin I also have this problem
> 
> * code version 1.49.2
> * VsCodeFileHeader version 0.5.0
> 
> Out of the box it works fine, but when I setup a custom template the problem occurs.
> 
> ```
>     "fileheader.body": true,
>     "fileheader.author": "Daniele Bellavista",
>     "fileheader.custom_template_path": "C:\\Users\\danie\\source\\VsCode\\templates",
>     "fileheader.ignore": ["*.tmpl"]
> ```
> 
> ```
> PS C:\Users\danie\source\VsCode\templates> cat .\header\JavaScript.tmpl
> 
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  * @Last Modified by:   {{last_modified_by}}
>  * @Last Modified time: {{last_modified_time}}
>  */
> ```
> 
> When creating a Javascript file, the header is inserted continuously until the file is closed.

![image](https://user-images.githubusercontent.com/21964908/94428208-e6a83a80-01c2-11eb-9531-2b75b199604c.png)

**Comment by caizhengxin** [comment]
> @caizhengxin I also have this problem
> 
> * code version 1.49.2
> * VsCodeFileHeader version 0.5.0
> 
> Out of the box it works fine, but when I setup a custom template the problem occurs.
> 
> ```
>     "fileheader.body": true,
>     "fileheader.author": "Daniele Bellavista",
>     "fileheader.custom_template_path": "C:\\Users\\danie\\source\\VsCode\\templates",
>     "fileheader.ignore": ["*.tmpl"]
> ```
> 
> ```
> PS C:\Users\danie\source\VsCode\templates> cat .\header\JavaScript.tmpl
> 
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  * @Last Modified by:   {{last_modified_by}}
>  * @Last Modified time: {{last_modified_time}}
>  */
> ```
> 
> When creating a Javascript file, the header is inserted continuously until the file is closed.
![image](https://user-images.githubusercontent.com/21964908/94429580-1b1cf600-01c5-11eb-88ad-218f10a8b51c.png)

Windows and Linux os no problem.

**Comment by dbellavista** [comment]
Hi!
Sorry you are right the default template works.

Could you try with this?

```
/*
 * @Author: {{author}}
 * @Date:   {{create_time}}
 */
```

Also, this template:

```
/*
 * @Author: {{author}}
 * @Date:   {{create_time}}
 * @Last Modified by:   {{last_modified_by}}
 */
```

causes:

```
[2020-09-28 13:57:12.001] [exthost] [error] onWillSaveTextDocument-listener from extension 'jankincai.vscodefileheader' threw ERROR
[2020-09-28 13:57:12.006] [exthost] [error] Error: Illegal value for `line`
	at d._lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:535:222)
	at Object.lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:534:181)
	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:344:37
	at t.ExtHostTextEditor.edit (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:242)
	at updateHeader (c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:342:12)
	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:437:13
	at t.ExtHostDocumentSaveParticipant._deliverEventAsync (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:150)
	at t.ExtHostDocumentSaveParticipant._deliverEventAsyncAndBlameBadListeners (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:396)
	at t.ExtHostDocumentSaveParticipant.$participateInSave (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:98)
	at g._doInvokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
	at g._invokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
	at g._receiveRequest (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
	at g._receiveOneMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
	at p.acceptChunk (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by dbellavista** [comment]
![image](https://user-images.githubusercontent.com/1540321/94429771-235c3d80-0193-11eb-93df-cd97ac6a09d6.png)

**Comment by caizhengxin** [comment]
> Hi!
> Sorry you are right the default template works.
> 
> Could you try with this?
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  */
> ```
> 
> Also, this template:
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  * @Last Modified by:   {{last_modified_by}}
>  */
> ```
> 
> causes:
> 
> ```
> [2020-09-28 13:57:12.001] [exthost] [error] onWillSaveTextDocument-listener from extension 'jankincai.vscodefileheader' threw ERROR
> [2020-09-28 13:57:12.006] [exthost] [error] Error: Illegal value for `line`
> 	at d._lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:535:222)
> 	at Object.lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:534:181)
> 	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:344:37
> 	at t.ExtHostTextEditor.edit (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:242)
> 	at updateHeader (c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:342:12)
> 	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:437:13
> 	at t.ExtHostDocumentSaveParticipant._deliverEventAsync (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:150)
> 	at t.ExtHostDocumentSaveParticipant._deliverEventAsyncAndBlameBadListeners (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:396)
> 	at t.ExtHostDocumentSaveParticipant.$participateInSave (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:98)
> 	at g._doInvokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
> 	at g._invokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
> 	at g._receiveRequest (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
> 	at g._receiveOneMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
> 	at t.PersistentProtocol._receiveMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at p.acceptChunk (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
> 	at Socket.t (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
> 	at Socket.emit (events.js:223:5)
> 	at addChunk (_stream_readable.js:309:12)
> 	at readableAddChunk (_stream_readable.js:290:11)
> 	at Socket.Readable.push (_stream_readable.js:224:10)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
> ```

No, this is the basis for judging the head

**Comment by caizhengxin** [comment]
> Hi!
> Sorry you are right the default template works.
> 
> Could you try with this?
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  */
> ```
> 
> Also, this template:
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  * @Last Modified by:   {{last_modified_by}}
>  */
> ```
> 
> causes:
> 
> ```
> [2020-09-28 13:57:12.001] [exthost] [error] onWillSaveTextDocument-listener from extension 'jankincai.vscodefileheader' threw ERROR
> [2020-09-28 13:57:12.006] [exthost] [error] Error: Illegal value for `line`
> 	at d._lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:535:222)
> 	at Object.lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:534:181)
> 	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:344:37
> 	at t.ExtHostTextEditor.edit (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:242)
> 	at updateHeader (c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:342:12)
> 	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:437:13
> 	at t.ExtHostDocumentSaveParticipant._deliverEventAsync (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:150)
> 	at t.ExtHostDocumentSaveParticipant._deliverEventAsyncAndBlameBadListeners (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:396)
> 	at t.ExtHostDocumentSaveParticipant.$participateInSave (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:98)
> 	at g._doInvokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
> 	at g._invokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
> 	at g._receiveRequest (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
> 	at g._receiveOneMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
> 	at t.PersistentProtocol._receiveMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at p.acceptChunk (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
> 	at Socket.t (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
> 	at Socket.emit (events.js:223:5)
> 	at addChunk (_stream_readable.js:309:12)
> 	at readableAddChunk (_stream_readable.js:290:11)
> 	at Socket.Readable.push (_stream_readable.js:224:10)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
> ```

You can only increase on the original basis

**Comment by caizhengxin** [comment]
> Hi!
> Sorry you are right the default template works.
> 
> Could you try with this?
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  */
> ```
> 
> Also, this template:
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  * @Last Modified by:   {{last_modified_by}}
>  */
> ```
> 
> causes:
> 
> ```
> [2020-09-28 13:57:12.001] [exthost] [error] onWillSaveTextDocument-listener from extension 'jankincai.vscodefileheader' threw ERROR
> [2020-09-28 13:57:12.006] [exthost] [error] Error: Illegal value for `line`
> 	at d._lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:535:222)
> 	at Object.lineAt (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:534:181)
> 	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:344:37
> 	at t.ExtHostTextEditor.edit (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:242)
> 	at updateHeader (c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:342:12)
> 	at c:\Users\danie\.vscode\extensions\jankincai.vscodefileheader-0.5.0\out\extension.js:437:13
> 	at t.ExtHostDocumentSaveParticipant._deliverEventAsync (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:150)
> 	at t.ExtHostDocumentSaveParticipant._deliverEventAsyncAndBlameBadListeners (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:396)
> 	at t.ExtHostDocumentSaveParticipant.$participateInSave (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:98)
> 	at g._doInvokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:464)
> 	at g._invokeHandler (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:860:156)
> 	at g._receiveRequest (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:858:817)
> 	at g._receiveOneMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:857:623)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:855:691
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1047:649
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at v.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
> 	at t.PersistentProtocol._receiveMessage (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
> 	at l.fire (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:475)
> 	at p.acceptChunk (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
> 	at c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
> 	at Socket.t (c:\Users\danie\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
> 	at Socket.emit (events.js:223:5)
> 	at addChunk (_stream_readable.js:309:12)
> 	at readableAddChunk (_stream_readable.js:290:11)
> 	at Socket.Readable.push (_stream_readable.js:224:10)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
> ```
Example:
![image](https://user-images.githubusercontent.com/21964908/94432700-b7e19280-01c9-11eb-86b9-6591030b834d.png)

**Comment by dbellavista** [comment]
Sorry I do not understand... So I cannot modify templates but only add them?

I tried with

```
    "fileheader.file_suffix_mapping": {
        ".js": "MyJavascript"
    },
```

And created `MyJavaScript.tmpl` with

```
/*
 * @Author: {{author}}
 * @Date:   {{create_time}}
 */
```

However the "eternal loop problem" persists

**Comment by caizhengxin** [comment]
> Sorry I do not understand... So I cannot modify templates but only add them?
> 
> I tried with
> 
> ```
>     "fileheader.file_suffix_mapping": {
>         ".js": "MyJavascript"
>     },
> ```
> 
> And created `MyJavaScript.tmpl` with
> 
> ```
> /*
>  * @Author: {{author}}
>  * @Date:   {{create_time}}
>  */
> ```
> 
> However the "eternal loop problem" persists

No, You cannot delete the original header comments, but you can add emails and other content

**Comment by dbellavista** [comment]
Ok got it. Any chance you could to support arbitrary custom header templates?

**Comment by caizhengxin** [comment]
Sorry, No way, Can't judge whether the head comment exists

**Comment by caizhengxin** [comment]
> Ok got it. Any chance you could to support arbitrary custom header templates?

Sorry, No way, Can't judge whether the head comment exists

**Comment by rollecode** [comment]
I have the same problem on macOS Catalina and latest version of this extension. It just adds another header if I add header from context menu. If I have auto save settings on it goes on forever loop like others have explained.

Here's a screen cap:

<img src="https://i.imgur.com/PJzCjd6.gif">

[Here](https://github.com/ronilaukkarinen/vscode-settings/blob/master/fileheaders/header/PHP.tmpl) is my current template.

**Comment by caizhengxin** [comment]
> I have the same problem on macOS Catalina and latest version of this extension. It just adds another header if I add header from context menu. If I have auto save settings on it goes on forever loop like others have explained.
> 
> Here's a screen cap:
> 
> ![](https://camo.githubusercontent.com/24cb9db4a2dc7fc5a3e3819dc80664f8bc607616/68747470733a2f2f692e696d6775722e636f6d2f504a7a436a64362e676966)
> 
> [Here](https://github.com/ronilaukkarinen/vscode-settings/blob/master/fileheaders/header/PHP.tmpl) is my current template.

Hi, Cannot delete the default template header.

![image](https://user-images.githubusercontent.com/21964908/97072510-02acc980-1613-11eb-872f-fbb790ad40aa.png)

**Comment by caizhengxin** [comment]
> > I have the same problem on macOS Catalina and latest version of this extension. It just adds another header if I add header from context menu. If I have auto save settings on it goes on forever loop like others have explained.
> > Here's a screen cap:
> > ![](https://camo.githubusercontent.com/24cb9db4a2dc7fc5a3e3819dc80664f8bc607616/68747470733a2f2f692e696d6775722e636f6d2f504a7a436a64362e676966)
> > [Here](https://github.com/ronilaukkarinen/vscode-settings/blob/master/fileheaders/header/PHP.tmpl) is my current template.
> 
> Hi, Cannot delete the default template header.
> 
> ![image](https://user-images.githubusercontent.com/21964908/97072510-02acc980-1613-11eb-872f-fbb790ad40aa.png)

You can only add

**Comment by rollecode** [comment]
But the whole point of file header is to be able to replace the current file header on save. If not, why is there on save feature if it just causes an endless loop? This defies all kind of logic.

Some other plugins do this, but they don't have as many variables as your plugin.

**Comment by caizhengxin** [comment]
> But the whole point of file header is to be able to replace the current file header on save. If not, why is there on save feature if it just causes an endless loop? This defies all kind of logic.
> 
> Some other plugins do this, but they don't have as many variables as your plugin.

{
    "fileheader.save": false,
}

# Set false, Need to add comments manually
ctrl + alt + i

**Comment by caizhengxin** [comment]
> But the whole point of file header is to be able to replace the current file header on save. If not, why is there on save feature if it just causes an endless loop? This defies all kind of logic.
> 
> Some other plugins do this, but they don't have as many variables as your plugin.

Because you changed the original content, I can’t tell if the comment exists, which causes it to be inserted every time

**Comment by rollecode** [comment]
> > But the whole point of file header is to be able to replace the current file header on save. If not, why is there on save feature if it just causes an endless loop? This defies all kind of logic.
> > Some other plugins do this, but they don't have as many variables as your plugin.
> 
> Because you changed the original content, I can’t tell if the comment exists, which causes it to be inserted every time

Yeah but that's the deal breaker here.

So consider this as a feature request (if did not already pick that up): Change the logic to recognize the content from the template so that it CAN tell if the comment exists so this wouldn't happen.

**Comment by caizhengxin** [comment]
> > > But the whole point of file header is to be able to replace the current file header on save. If not, why is there on save feature if it just causes an endless loop? This defies all kind of logic.
> > > Some other plugins do this, but they don't have as many variables as your plugin.
> > 
> > 
> > Because you changed the original content, I can’t tell if the comment exists, which causes it to be inserted every time
> 
> Yeah but that's the deal breaker here.
> 
> So consider this as a feature request (if did not already pick that up): Change the logic to recognize the content from the template so that it CAN tell if the comment exists so this wouldn't happen.

Determine whether the header exists,  can make a configuration file later.

**Comment by caizhengxin** [comment]
> > > But the whole point of file header is to be able to replace the current file header on save. If not, why is there on save feature if it just causes an endless loop? This defies all kind of logic.
> > > Some other plugins do this, but they don't have as many variables as your plugin.
> > 
> > 
> > Because you changed the original content, I can’t tell if the comment exists, which causes it to be inserted every time
> 
> Yeah but that's the deal breaker here.
> 
> So consider this as a feature request (if did not already pick that up): Change the logic to recognize the content from the template so that it CAN tell if the comment exists so this wouldn't happen.

![image](https://user-images.githubusercontent.com/21964908/100469678-b07b2e80-3111-11eb-85ee-406745e4f3fc.png)
