### ISSUE TITLE
Extension replaces the last_modified_by and last_modified_time when editing tmpl file

### ISSUE THREAD

**Issue by dbellavista** [caizhengxin/vscodefileheader#7]
* code version 1.49.2
* VsCodeFileHeader version 0.5.0

I tried to set

```
    "fileheader.ignore": ["*.tmpl"]
```

But to no avail

**Comment by caizhengxin** [comment]
> * code version 1.49.2
> * VsCodeFileHeader version 0.5.0
> 
> I tried to set
> 
> ```
>     "fileheader.ignore": ["*.tmpl"]
> ```
> 
> But to no avail

Currently, the header file is not inserted, avail

**Comment by caizhengxin** [comment]
> * code version 1.49.2
> * VsCodeFileHeader version 0.5.0
> 
> I tried to set
> 
> ```
>     "fileheader.ignore": ["*.tmpl"]
> ```
> 
> But to no avail

Thank you for your feedback, I will fix it as soon as possible

**Comment by caizhengxin** [comment]
> * code version 1.49.2
> * VsCodeFileHeader version 0.5.0
> 
> I tried to set
> 
> ```
>     "fileheader.ignore": ["*.tmpl"]
> ```
> 
> But to no avail

Hi, ignore file bug, See v0.5.1
