### ISSUE TITLE
Not working in ".h" file

### ISSUE THREAD

**Issue by rhdlilj** [caizhengxin/vscodefileheader#8]
vscode: 1.51.1
vscodefileheader: 0.5.1

``ctrl + alt + i`` can't  insert comment in ``.h`` file

**Comment by caizhengxin** [comment]
> vscode: 1.51.1
> vscodefileheader: 0.5.1
> 
> `ctrl + alt + i` can't insert comment in `.h` file

    "fileheader.file_suffix_mapping": {
        ".h": "C"
    }
